services:
  api:
    image: api-rest-image
    environment:
      - DATASOURCE_PASSWORD=1234
      - DATASOURCE_URL=jdbc:postgresql://database:5432/api-rest
    ports:
      - "8080:8080"
    depends_on:
      - database
  database:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: api-rest