#spring.application.name=api
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/api-rest
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
