#spring.application.name=api
spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/api-rest}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:1234}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
